### PR TITLE
Add custom content type and encoding in html head

### PR DESCRIPTION
**Pull request by simplicbe**
Add custom content type and encoding in html head. For example:

`text/html; charset=utf-8`

### CODE REVIEW

**Comment by Sicos1977** [comment]
I merged all your pull request and did a little bit of code refactoring so that all the code follows the same coding rules.

**Comment by simplicbe** [comment]
Thanks a lot for that fast answer!

**Comment by Sicos1977** [comment]
Just for my own curiosity... for what do you use the MSGReader .... document management or something like that?

**Comment by simplicbe** [comment]
Yep, we are developing document management/crm/cdn solutions and we use it to extract information from msg files and to display msg files in a document viewer. We also support a few open source projects and also have a lot of own open source projects.

**Comment by Sicos1977** [comment]
I did write more libraries to handle documents.. you can find them overhere --> https://github.com/Sicos1977

I'm also working in the document management business for the biggest insurance company in the Netherlands.. so lot of it is used over there and is proven technology in a production environment :-)

**Pull request merged**
